### ISSUE TITLE
Missing config param

### ISSUE THREAD

**Issue by janrothen** [michaeljtbrooks/raspiled#7]
`'pig_port'    : 8888`

is missing in src/raspiled.conf.TEMPLATE

**Comment by josuemtzmo** [comment]
Hello Janrothen, the `'pig_port'` : 8888` was replaced by `'pi_port' : 8888`. If you want to change the GPIO port, you should modify that `pi_port` at src/raspiled.conf.TEMPLATE.

**Comment by janrothen** [comment]
I got an error when running ./src/raspiled_listener.py without that entry in raspiled.conf and the web interface was not starting up.

When debugging raspiled_listener.py I found that the config param pig_port is missing. Adding it to the raspiled.conf fixed that problem for me.

**Comment by josuemtzmo** [comment]
Thanks for raising this issue, we will fix it in the next upgrade.

**Comment by michaeljtbrooks** [comment]
Lovely, well spotted @janrothen!

Thank you for the bug report and more importantly for giving Raspiled a go.

I've got some time this coming weekend to merge in Josue's latest code and address some bugs.

**Comment by michaeljtbrooks** [comment]
Fixed in #9 c37711b22c126f548db2ae2b89d73889f6b374ac
