### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by Flowsche** [michaeljtbrooks/raspiled#8]
Hi,
first of all, thanks for the cool project and your support 8)

I'm getting errors during startup of the process.
I tried multiple folders, full re-installed all, also the dev branch but the error is still the same:

` python ./src/raspiled_listener.py
[14:00:42 RASPILED] PIGPIOD is running! PID: 899
[14:00:43 RASPILED] Using config file: /home/pi/Downloads/src/raspiled.conf
[14:00:43 RASPILED] [STARTING] Raspiled Listener with PID 1075
Unhandled error in Deferred:
`
It stops at this point and nothing more. :(
Some ideas?

Greetings

**Comment by josuemtzmo** [comment]
Hello Flowsche,

It may be possible you left a **Raspiled** process running in the background. That's the only way I've been able to replicate the issue. Could you try killing all python processes `pkill python` and retry running `python ./src/raspiled_listener.py`. 

Cheers

**Comment by Flowsche** [comment]
This didn't help. I'll try a complete new raspi image and go through all steps one by one again. Perhaps there is still something other wrong here, i tried an other web gui for leds before.
Thanks anyway

**Comment by josuemtzmo** [comment]
Hello, 

As far as I know, this may be a conflict of ports on Twisted. Could you check you are not using the same port (check `pi_port`) for another purpose, by default it's 9090, and you can change it at the `raspiled.conf` file.

Cheers

**Comment by Flowsche** [comment]
Yes true, it was the Port...
The default Port in the config is 8888 but after changing to 9090 it works.
Perhaps it would be better for other users too if you change it in the template file? :)

Greetings and Thanks!
